import { expect, test } from '@playwright/test'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFileSync } from 'node:child_process'
import { rmSync } from 'node:fs'
import { randomUUID } from 'node:crypto'

const python = fileURLToPath(new URL(process.platform === 'win32' ? '../../.venv/Scripts/python.exe' : '../../.venv/bin/python', import.meta.url))

function clearTestDatabase() {
  const database = process.env.FEEDBACK_E2E_DATABASE
  if (!database || !/^feedback_reward_e2e_[0-9a-f]{32}$/.test(database)) throw new Error('Refusing to clear a non-test database')
  execFileSync(python, ['-c', 'import sys; from pymongo import MongoClient; client = MongoClient("mongodb://127.0.0.1:27017/", serverSelectionTimeoutMS=3000); client.drop_database(sys.argv[1]); client.close()', database])
}

test.beforeEach(() => clearTestDatabase())
test.afterAll(() => {
  clearTestDatabase()
  if (process.env.FEEDBACK_E2E_TICKETS) rmSync(process.env.FEEDBACK_E2E_TICKETS, { force: true })
})

const screenshots = fileURLToPath(new URL('../../docs/screenshots/', import.meta.url))
const appreciation = 'I was really struggling to get the pista cookies for the past few days considering everybody loves it. The stock runs out whenever I visit the store. Thankfully, Mr. Joe helped me with the timings when the product will be restocked and I was finally able to get it today for my niece who loves it.'

test('customer journey validates contact, Sparks and stars then confirms submission', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Tell us about your visit' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Analyse feedback', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Submit Feedback', exact: true }).click()
  await expect(page.getByLabel('Customer Name')).toBeFocused()
  await page.getByLabel('Customer Name').fill('Demo Customer')
  await page.getByLabel('Feedback (required)', { exact: true }).fill('The checkout charged twice for my order yesterday and I lost money.')
  await page.getByRole('radio', { name: '2 stars: Poor', exact: true }).check()
  await expect(page.locator('.star-rating small')).toHaveText('Poor')
  await page.getByRole('button', { name: 'Submit Feedback', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('email address or phone')
  await page.getByLabel('Email address', { exact: true }).fill('not-an-email')
  await page.getByRole('button', { name: 'Submit Feedback', exact: true }).click()
  expect(await page.getByLabel('Email address', { exact: true }).evaluate((element: HTMLInputElement) => element.validity.valid)).toBe(false)
  await page.getByLabel('Email address', { exact: true }).fill('demo@example.com')
  await page.getByRole('radio', { name: 'Yes', exact: true }).check()
  await expect(page.getByLabel('Sparks ID')).toBeVisible()
  await page.getByRole('button', { name: 'Submit Feedback', exact: true }).click()
  await expect(page.getByLabel('Sparks ID')).toBeFocused()
  await page.getByLabel('Sparks ID').fill('SPARKS123')
  const saved = page.waitForResponse('**/api/customer-feedback')
  await page.getByRole('button', { name: 'Submit Feedback', exact: true }).click()
  const identity = (await (await saved).json()).case_id
  await expect(page.getByRole('status')).toContainText('Feedback submitted successfully.')
  await expect(page.getByLabel('Customer Name')).toHaveValue('')
  await expect(page.getByLabel('Sparks ID')).toHaveCount(0)
  await expect(page.getByTestId('notification-count')).toHaveText('1')
  const detail = await (await page.request.get(`/api/colleague/feedback-cases/${identity}`)).json()
  expect(detail.customer.sparks_id).toBe('SPARKS123')
  expect(detail.reward_assessment.final_decision).toBeNull()
  await page.screenshot({ path: path.join(screenshots, 'customer-success-desktop.png'), fullPage: true })
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: path.join(screenshots, 'customer-success-mobile.png'), fullPage: true })
})

test('customer journey retries lost responses without duplicate cases or clearing input', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Customer Name').fill('Phone Customer')
  await page.getByLabel('Phone number', { exact: true }).fill('abc')
  await page.getByLabel('Feedback (required)', { exact: true }).fill('The fitting room lock broke during my visit yesterday.')
  await page.getByRole('radio', { name: '1 star: Very Poor' }).check()
  await page.getByRole('button', { name: 'Submit Feedback', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('7 to 15 digits')
  await page.getByLabel('Phone number', { exact: true }).fill('+44 7700 900123')
  const ids: string[] = []
  let release!: () => void
  const hold = new Promise<void>(resolve => { release = resolve })
  await page.route('**/api/customer-feedback', async route => {
    ids.push(route.request().postDataJSON().submission_id)
    if (ids.length === 1) await hold
    const response = await route.fetch()
    if (ids.length === 1) await route.fulfill({ status: 503, json: { detail: 'Confirmation lost. Please retry.' } })
    else await route.fulfill({ response })
  })
  await page.getByRole('button', { name: 'Submit Feedback', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Submitting feedback...' })).toBeDisabled()
  await expect(page.getByLabel('Customer Name')).toBeDisabled()
  release()
  await expect(page.getByRole('alert')).toContainText('Please retry')
  await expect(page.getByLabel('Customer Name')).toHaveValue('Phone Customer')
  await page.getByRole('button', { name: 'Submit Feedback', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Feedback submitted successfully.')
  expect(ids).toHaveLength(2)
  expect(ids[0]).toBe(ids[1])
  const result = await (await page.request.get('/api/colleague/feedback-cases')).json()
  expect(result.total).toBe(1)
  const detail = await (await page.request.get(`/api/colleague/feedback-cases/${ids[0]}`)).json()
  expect(detail.customer.sparks_id).toBeNull()
  expect(detail.customer.email).toBeNull()
})

test('live review receives cross-tab notifications and records reward and email simulation', async ({ page, context }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/#resolution-hub')
  await expect(page.getByText('No feedback insights are available yet.')).toBeVisible()
  const customer = await context.newPage()
  await customer.goto('/')
  await customer.getByLabel('Store', { exact: true }).selectOption('bluewater')
  await customer.getByLabel('Customer Name').fill('Review Customer')
  await customer.getByLabel('Email address', { exact: true }).fill('review@example.com')
  await customer.getByLabel('Feedback (required)', { exact: true }).fill('The checkout charged twice for my order yesterday and I lost money.')
  await customer.getByRole('radio', { name: '2 stars: Poor' }).check()
  await customer.getByRole('button', { name: 'Submit Feedback', exact: true }).click()
  await expect(page.getByTestId('notification-count')).toHaveText('1', { timeout: 5000 })
  await expect(page.locator('.loop-case')).toHaveCount(1)
  await page.getByRole('link', { name: 'New feedback notifications: 1', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Review Customer', exact: true })).toBeVisible()
  await expect(page.getByTestId('notification-count')).toHaveText('0')
  await expect(page.getByRole('region', { name: 'Model decision support' })).toContainText('Negative')
  await expect(page.getByRole('form', { name: 'Customer clarification' })).toHaveCount(0)
  await page.getByLabel('Update case status').selectOption('In Progress')
  await page.getByLabel('Colleague name').fill('Demo Colleague')
  await page.getByLabel('Decision reason').fill('Specific payment issue reviewed.')
  await page.getByLabel('Internal note (optional)').fill('Payment references checked.')
  await page.getByRole('button', { name: 'Confirm Reward Eligible', exact: true }).click()
  await expect(page.locator('.case-decision')).toContainText('Colleague decision: Reward Eligible')
  await expect(page.getByRole('region', { name: 'Customer Communication' })).toContainText('eligible for a reward')
  await page.getByRole('button', { name: 'Send customer update', exact: true }).click()
  await expect(page.locator('.loop-notice')).toContainText('Customer notification email has been sent successfully.')
  await expect(page.locator('.loop-notice')).toContainText('POC simulation')
  await expect(page.getByRole('region', { name: 'Action history' })).toContainText('reward_eligible')
  await page.getByLabel('Update case status').selectOption('Resolved')
  await page.getByRole('button', { name: 'Confirm Reward Eligible', exact: true }).click()
  await expect(page.locator('.loop-detail-heading')).toContainText('Resolved')
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    const filters = await page.locator('.loop-toolbar').boundingBox()
    const workspace = await page.locator('.loop-workspace').boundingBox()
    expect(workspace!.y).toBeGreaterThan(filters!.y + filters!.height)
  }
  await page.screenshot({ path: path.join(screenshots, 'resolution-hub-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: path.join(screenshots, 'resolution-hub-mobile.png'), fullPage: true })
  await page.reload()
  await expect(page.locator('.case-decision')).toContainText('Colleague decision: Reward Eligible')
  await expect(page.locator('.loop-ownership')).toContainText('Recorded (POC simulation)')
  await page.getByLabel('Choose Store').selectOption('marble-arch')
  await expect(page.getByText('No matching cases.', { exact: true })).toBeVisible()
  await page.getByLabel('Choose Store').selectOption('bluewater')
  await page.getByLabel('Case Status', { exact: true }).selectOption('Opened')
  await expect(page.getByText('No matching cases.', { exact: true })).toBeVisible()
  await page.getByLabel('Case Status', { exact: true }).selectOption('Resolved')
  await page.getByLabel('Search Cases').fill('charged twice')
  await expect(page.locator('.loop-case')).toHaveCount(1)
  await page.getByLabel('Reward decision', { exact: true }).selectOption('Not Eligible')
  await expect(page.locator('.loop-case')).toHaveCount(0)
  expect(errors).toEqual([])
})

test('live review fallback polls and phone-only communication never claims email delivery', async ({ page }) => {
  await page.routeWebSocket('**/api/colleague/events', socket => socket.close())
  await page.goto('/#resolution-hub')
  await expect(page.getByTestId('notification-count')).toHaveText('0')
  const response = await page.request.post('/api/customer-feedback', { data: {
    submission_id: randomUUID(), name: 'Phone Review', phone_number: '+44 7700 900123', is_sparks_customer: false,
    feedback: 'Good', rating: 3, store_id: 'marble-arch',
  } })
  expect(response.ok()).toBe(true)
  await expect(page.getByTestId('notification-count')).toHaveText('1', { timeout: 15000 })
  await page.getByRole('link', { name: 'New feedback notifications: 1', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Phone Review' })).toBeVisible()
  await page.getByLabel('Colleague name').fill('Demo Colleague')
  await page.getByLabel('Decision reason').fill('Insufficient useful information for a reward.')
  await page.getByLabel('Internal note (optional)').fill('Draft note retained during communication.')
  await page.getByRole('button', { name: 'Send customer update' }).click()
  await expect(page.locator('.loop-notice')).toContainText('Customer notification has been recorded.')
  await expect(page.getByLabel('Internal note (optional)')).toHaveValue('Draft note retained during communication.')
  await page.getByRole('button', { name: 'Keep Awaiting Review' }).click()
  await expect(page.locator('.loop-notice')).toContainText('Colleague decision recorded.')
  await page.getByRole('button', { name: 'Confirm Not Eligible' }).click()
  await expect(page.locator('.case-decision')).toContainText('Colleague decision: Not Eligible')
  await page.getByRole('button', { name: 'Send customer update' }).click()
  await expect(page.locator('.loop-notice')).toContainText('Customer notification has been recorded.')
  await expect(page.locator('.loop-notice')).not.toContainText('email')
  await expect(page.getByRole('region', { name: 'Customer Communication' })).toContainText('does not currently meet')
})

test('live reward recommendations and responsive screenshots', async ({ page }) => {
  const exceptions: string[] = []
  page.on('pageerror', error => exceptions.push(error.message))
  await page.goto('/#feedback')
  for (const [sample, sentiment, decision] of [
    ['Store improvement', 'Negative', 'Eligible'],
    ['Helpful service', 'Positive', 'Eligible'],
    ['Mixed experience', 'Neutral', 'Eligible'],
    ['Generic praise', 'Positive', 'Not eligible'],
  ]) {
    await page.getByLabel('Sample feedback').selectOption(sample)
    await expect(page.getByRole('heading', { name: 'Awaiting feedback analysis', exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
    await expect(page.getByRole('heading', { name: decision, exact: true })).toBeVisible()
    if (sample !== 'Generic praise') await expect(page.locator('.sentiment')).toHaveText(sentiment)
    await expect(page.getByRole('meter')).toHaveCount(2)
    await expect(page.locator('.feedback-quote blockquote')).toHaveText(await page.getByLabel('Customer feedback', { exact: true }).inputValue())
  }
  for (const feedback of ['Hi', 'Hello', 'Thank you very much', 'qwerty asdfgh zxcvbn']) {
    await page.getByLabel('Customer feedback', { exact: true }).fill(feedback)
    await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Not eligible', exact: true })).toBeVisible()
    await expect(page.locator('.genuine-label')).toHaveText('No')
    await expect(page.locator('.explanation').first()).toContainText(/No meaningful customer feedback|General praise/)
  }
  for (const feedback of [appreciation, `Hi! ${appreciation} Thank you!`]) {
    await page.getByLabel('Customer feedback', { exact: true }).fill(feedback)
    await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Eligible', exact: true })).toBeVisible()
    await expect(page.locator('.genuine-label')).toHaveText('Yes')
    await expect(page.locator('.feedback-quote blockquote')).toHaveText(feedback)
  }
  for (const feedback of [
    'The cakes are really good but always sold out. Would be nice if it can be stocked frequently.',
    'The bakery items are fresh, but most popular products are already sold out by evening. It would help if stock is replenished more frequently.',
    'cakes sold out by 5pm',
    'cakes sold out. please restock before lunch',
    'cakes always soldout pls restock',
  ]) {
    await page.getByLabel('Customer feedback', { exact: true }).fill(feedback)
    await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Eligible', exact: true })).toBeVisible()
    await expect(page.locator('.genuine-label')).toHaveText('Yes')
    await expect(page.getByRole('heading', { name: 'Minor complaint', exact: true })).toBeVisible()
    await expect(page.getByRole('region', { name: 'Complaint ticket' })).toContainText('Normal')
  }
  for (const feedback of ['cakes sold out', 'nice cakes but no stock', 'The bakery items are sold out.', 'pls restock bread']) {
    await page.getByLabel('Customer feedback', { exact: true }).fill(feedback)
    await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Not eligible', exact: true })).toBeVisible()
    await expect(page.locator('.genuine-label')).toHaveText('No')
    await expect(page.locator('.explanation').first()).toContainText(/More details are needed|more specific, useful context/)
  }
  await page.getByRole('button', { name: 'Clear feedback' }).click()
  await expect(page.getByRole('button', { name: 'Analyse feedback', exact: true })).toBeDisabled()
  await page.getByLabel('Customer feedback', { exact: true }).fill('123!')
  await expect(page.getByRole('button', { name: 'Analyse feedback', exact: true })).toBeDisabled()
  await page.getByLabel('Sample feedback').selectOption('Store improvement')
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Eligible', exact: true })).toBeVisible()
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    const input = await page.locator('.input-section').boundingBox()
    const result = await page.locator('.result-section').boundingBox()
    expect(input).not.toBeNull()
    expect(result).not.toBeNull()
    if (width >= 768) expect(result!.x).toBeGreaterThan(input!.x)
    else expect(result!.y).toBeGreaterThan(input!.y)
  }
  await page.screenshot({ path: path.join(screenshots, 'desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: path.join(screenshots, 'mobile.png'), fullPage: true })
  expect(exceptions).toEqual([])
})

test('loading lock, server error, and successful retry', async ({ page }) => {
  await page.goto('/#feedback')
  let releaseRequest!: () => void
  const holdRequest = new Promise<void>(resolve => { releaseRequest = resolve })
  await page.route('**/api/predict', async route => {
    await holdRequest
    await route.fulfill({ status: 503, contentType: 'application/json', body: '{"detail":"Models unavailable"}' })
  })
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Analysing feedback...' })).toBeDisabled()
  await expect(page.getByLabel('Customer feedback', { exact: true })).toBeDisabled()
  releaseRequest()
  await expect(page.getByRole('alert')).toContainText('Models are unavailable')
  await page.unroute('**/api/predict')
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Eligible', exact: true })).toBeVisible()
})

test('insights track saved results, filters, navigation and refresh persistence', async ({ page }) => {
  const exceptions: string[] = []
  page.on('pageerror', error => exceptions.push(error.message))
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.clock.install()
  await page.goto('/#insights')
  await expect(page.getByRole('heading', { name: 'No analyses yet' })).toBeVisible()
  await expect(page.getByTestId('analytics-total')).toHaveText('0')
  await expect(page.getByRole('button', { name: 'Refresh saved feedback' })).toBeEnabled()
  await page.getByRole('link', { name: 'Feedback', exact: true }).click()
  for (const sample of ['Store improvement', 'Helpful service']) {
    await page.getByLabel('Sample feedback').selectOption(sample)
    await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Eligible', exact: true })).toBeVisible()
  }
  await page.getByRole('link', { name: 'Insights', exact: true }).click()
  await expect(page.getByTestId('analytics-total')).toHaveText('2')
  await expect(page.getByRole('meter', { name: 'Positive share' })).toHaveAttribute('aria-valuenow', '50')
  await expect(page.getByRole('meter', { name: 'Negative share' })).toHaveAttribute('aria-valuenow', '50')
  await expect(page.getByRole('meter', { name: 'Neutral share' })).toHaveAttribute('aria-valuenow', '0')
  await expect(page.locator('.analytics tbody tr')).toHaveCount(2)
  await expect(page.getByRole('img', { name: /Feedback volume/ })).toHaveAttribute('aria-label', /2 analyses/)
  await page.getByLabel('Sentiment filter').selectOption('Negative')
  await expect(page.getByTestId('analytics-total')).toHaveText('1')
  await expect(page.locator('.analytics tbody')).toContainText('eye strain')
  await page.getByLabel('Sentiment filter').selectOption('Neutral')
  await expect(page.getByText('No feedback matches these filters.')).toBeVisible()
  await expect(page.getByTestId('analytics-total')).toHaveText('0')
  await page.getByLabel('Sentiment filter').selectOption('All')
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await expect(page.getByRole('heading', { name: 'Insight engine', exact: true })).toBeVisible()
    const metrics = await page.locator('.analytics-kpis').boundingBox()
    const charts = await page.locator('.analytics-charts').boundingBox()
    expect(charts!.y).toBeGreaterThanOrEqual(metrics!.y + metrics!.height)
  }
  await page.screenshot({ path: path.join(screenshots, 'analytics-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: path.join(screenshots, 'analytics-mobile.png'), fullPage: true })
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'Eligible', exact: true })).toBeVisible()
  await page.goForward()
  await expect(page.getByTestId('analytics-total')).toHaveText('2')
  await page.getByLabel('Time range').selectOption('hour')
  await page.clock.fastForward(61 * 60000)
  await expect(page.getByTestId('analytics-total')).toHaveText('0')
  await page.getByLabel('Time range').selectOption('session')
  await expect(page.getByTestId('analytics-total')).toHaveText('2')
  await page.getByRole('button', { name: 'Refresh saved feedback' }).click()
  await expect(page.getByTestId('analytics-total')).toHaveText('2')
  await page.reload()
  await expect(page.getByTestId('analytics-total')).toHaveText('2')
  await expect(page.locator('.analytics tbody tr')).toHaveCount(2)
  expect(exceptions).toEqual([])
})

test('insights exclude failed requests and update when analysis finishes on another page', async ({ page }) => {
  await page.goto('/#feedback')
  await page.route('**/api/predict', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"detail":"Models unavailable"}' }))
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Models are unavailable')
  await page.getByRole('link', { name: 'Insights', exact: true }).click()
  await expect(page.getByTestId('analytics-total')).toHaveText('0')
  await page.unroute('**/api/predict')
  await page.getByRole('link', { name: 'Feedback', exact: true }).click()
  let releaseRequest!: () => void
  const holdRequest = new Promise<void>(resolve => { releaseRequest = resolve })
  await page.route('**/api/predict', async route => {
    await holdRequest
    await route.continue()
  })
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Analysing feedback...' })).toBeDisabled()
  await page.getByRole('link', { name: 'Insights', exact: true }).click()
  await expect(page.getByTestId('analytics-total')).toHaveText('0')
  releaseRequest()
  await expect(page.getByTestId('analytics-total')).toHaveText('1')
  await expect(page.locator('.analytics tbody')).toContainText('eye strain')
})

test('compliments, colleague review and persistent complaint tickets', async ({ page }) => {
  await page.goto('/#feedback')
  await page.getByLabel('Sample feedback').selectOption('Baby clothes compliment')
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Eligible', exact: true })).toBeVisible()
  await expect(page.locator('.customer-response')).toContainText('Thank you')
  await expect(page.getByRole('region', { name: 'Complaint ticket' })).toHaveCount(0)

  await page.getByLabel('Sample feedback').selectOption('Needs review')
  const pendingResponse = page.waitForResponse('**/api/predict')
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  const pending = await (await pendingResponse).json()
  await expect(page.getByRole('heading', { name: 'Awaiting Colleague Review', exact: true })).toBeVisible()
  await expect(page.locator('.customer-response')).toContainText('Thank you for your feedback')
  await expect(page.getByRole('region', { name: 'Complaint ticket' })).toContainText('Priority attention')
  await expect(page.getByRole('region', { name: 'Complaint ticket' })).toContainText(pending.ticket.id)
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.getByRole('link', { name: 'Insights', exact: true }).click()
  await expect(page.locator('.analytics tbody')).toContainText('Awaiting Colleague Review')
  await page.reload()
  const stored = await page.request.get(`/api/tickets/${pending.ticket.id}`)
  expect(stored.ok()).toBe(true)
  expect(await stored.json()).toEqual(pending.ticket)

  await page.getByRole('link', { name: 'Feedback', exact: true }).click()
  await page.getByLabel('Customer feedback', { exact: true }).fill('qwerty asdfgh zxcvbn')
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Ignored', exact: true })).toBeVisible()
  await expect(page.locator('.customer-response')).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Complaint ticket' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Insights', exact: true }).click()
  await expect(page.getByTestId('analytics-total')).toHaveText('3')
})

test('retry reuses a ticket when its first confirmation is lost', async ({ page }) => {
  await page.goto('/#feedback')
  await page.getByLabel('Sample feedback').selectOption('Payment complaint')
  let openedTicket: { id: string } | undefined
  const submissionIds: string[] = []
  await page.route('**/api/predict', async route => {
    submissionIds.push(route.request().postDataJSON().submissionId)
    const response = await route.fetch()
    const result = await response.json()
    if (!openedTicket) {
      openedTicket = result.ticket
      await route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: 'Ticket storage unavailable. Please retry.' }) })
    } else {
      expect(result.ticket.id).toBe(openedTicket.id)
      await route.fulfill({ response })
    }
  })
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Ticket storage is unavailable')
  await expect(page.getByRole('heading', { name: 'Ticket opened', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Eligible', exact: true })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Complaint ticket' })).toContainText(openedTicket!.id)
  expect(submissionIds).toHaveLength(2)
  expect(submissionIds[0]).toBe(submissionIds[1])
})

test('legacy hub link opens the live empty Resolution Hub with only supported statuses', async ({ page }) => {
  await page.goto('/#closed-loop')
  await expect(page.getByRole('heading', { name: 'Feedback Resolution Hub', exact: true })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Feedback Resolution Hub', exact: true })).toHaveAttribute('aria-current', 'page')
  await expect(page.locator('#loop-status option')).toHaveText(['All statuses', 'Opened', 'In Progress', 'Resolved'])
  await expect(page.locator('.loop-case')).toHaveCount(0)
  await expect(page.getByText('No feedback insights are available yet.')).toBeVisible()
  await page.getByRole('link', { name: 'Customer Perspective', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Tell us about your visit' })).toBeVisible()
  await page.getByRole('link', { name: 'Store Colleague Perspective', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Analyse feedback', exact: true })).toBeVisible()
})

test('Sparks incentive recommendations and minor complaint review', async ({ page }) => {
  await page.goto('/#feedback')
  await page.getByLabel('Sample feedback').selectOption('Baby clothes compliment')
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Eligible', exact: true })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Sparks Customer (POC profile)' }).check()
  await expect(page.getByRole('heading', { name: 'Awaiting feedback analysis', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Eligible', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Incentive recommendation', exact: true })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Sparks Customer (POC profile)' }).uncheck()
  await page.getByLabel('Customer feedback', { exact: true }).fill('The colleague went above and beyond, finding my missing order and arranging delivery to my home.')
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Major compliment', exact: true })).toBeVisible()
  await expect(page.getByText('Standard reward · Points undecided · Not issued', { exact: true })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Sparks Customer (POC profile)' }).check()
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Eligible', exact: true })).toBeVisible()
  await expect(page.getByText('High-tier Sparks incentive · Points undecided · Not issued', { exact: true })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Sparks Customer (POC profile)' }).uncheck()
  await page.getByLabel('Customer feedback', { exact: true }).fill('cakes sold out')
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  await expect(page.locator('.customer-response')).toContainText('Thank you for your feedback')
  await expect(page.getByRole('form', { name: 'Customer clarification' })).toHaveCount(0)
  await expect(page.getByRole('region', { name: 'Complaint ticket' })).toHaveCount(0)
})

test('legacy clarification API remains compatible without a customer clarification journey', async ({ page }) => {
  const original = await (await page.request.post('/api/predict', { data: { feedback: 'The store is unsafe.', loyalCustomer: true } })).json()
  const payload = { feedbackId: original.feedbackId, ticketId: original.ticket.id, submissionId: randomUUID(),
    originalFeedback: original.feedback, feedback: 'The wheelchair ramp was blocked and I could not enter the store yesterday.', loyalCustomer: true }
  const updated = await page.request.post('/api/clarify', { data: payload })
  expect(updated.ok()).toBe(true)
  const result = await updated.json()
  expect(result.ticket.id).toBe(original.ticket.id)
  expect(await (await page.request.post('/api/clarify', { data: payload })).json()).toEqual(result)
  await page.goto('/#insights')
  await expect(page.getByTestId('analytics-total')).toHaveText('1')
  await page.getByRole('button', { name: `Open feedback ${original.feedbackId}` }).click()
  await expect(page.locator('.feedback-quote')).toContainText('wheelchair')
  await expect(page.getByRole('form', { name: 'Customer clarification' })).toHaveCount(0)
})

test('saved store and Sparks metadata survive refresh and a new tab', async ({ page, context }) => {
  await page.goto('/#feedback')
  await page.getByLabel('Feedback store', { exact: true }).selectOption('bluewater')
  await page.getByRole('checkbox', { name: 'Sparks Customer (POC profile)' }).check()
  await page.getByLabel('Sample feedback').selectOption('Needs review')
  const response = page.waitForResponse('**/api/predict')
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  const first = await (await response).json()
  await expect(page.getByRole('heading', { name: 'Awaiting Colleague Review', exact: true })).toBeVisible()
  await page.getByRole('link', { name: 'Insights', exact: true }).click()
  await page.reload()
  await expect(page.locator('.analytics tbody')).toContainText('M&S Bluewater')
  await expect(page.locator('.analytics tbody')).toContainText('Sparks Customer')
  await page.getByLabel('Store filter', { exact: true }).selectOption('bluewater')
  await page.getByLabel('Customer type', { exact: true }).selectOption('standard')
  await expect(page.getByTestId('analytics-total')).toHaveText('0')
  await page.getByLabel('Customer type', { exact: true }).selectOption('loyal')
  await expect(page.getByTestId('analytics-total')).toHaveText('1')
  await page.getByRole('button', { name: `Open feedback ${first.feedbackId}` }).click()
  await expect(page.getByLabel('Feedback store', { exact: true })).toHaveValue('bluewater')
  await expect(page.getByRole('checkbox', { name: 'Sparks Customer (POC profile)' })).toBeChecked()
  const other = await context.newPage()
  await other.goto('/#insights')
  await expect(other.getByTestId('analytics-total')).toHaveText('1')
  await expect(other.locator('.analytics tbody')).toContainText('unsafe')
  await expect(other.locator('.analytics tbody')).toContainText('Sparks Customer')
  const history = await (await other.request.get('/api/feedback')).json()
  expect(history.items[0].feedbackId).toBe(first.feedbackId)
  expect(history.items[0].ticket.id).toBe(first.ticket.id)
  expect(history.items[0].revision).toBe(0)
})

test('real ticket assignment, action history and customer follow-up survive refresh', async ({ page }) => {
  await page.goto('/#feedback')
  await page.getByLabel('Sample feedback').selectOption('Payment complaint')
  const prediction = page.waitForResponse('**/api/predict')
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  const saved = await (await prediction).json()
  const panel = page.getByRole('region', { name: 'Store follow-up', exact: true })
  await expect(panel.locator('.workflow-summary')).toContainText('Unassigned')
  await page.getByLabel('Assigned colleague', { exact: true }).fill('Alex Example')
  await page.getByLabel('Work status', { exact: true }).selectOption('in_progress')
  await page.getByLabel('Action taken', { exact: true }).fill('Checked both payment references with the payments team.')
  await panel.getByLabel('Customer Communication', { exact: true }).fill('Alex is your contact while we check the duplicate payment.')
  await page.getByLabel('Customer email (optional)', { exact: true }).fill('customer@example.com')
  await page.getByLabel('Customer permits storage and follow-up contact').check()
  const operations: string[] = []
  await page.route('**/api/tickets/*/workflow', async route => {
    if (route.request().method() !== 'PUT') return route.continue()
    operations.push(route.request().postDataJSON().operationId)
    const response = await route.fetch()
    if (operations.length === 1) await route.fulfill({ status: 503, json: { detail: 'Ticket storage unavailable. Retry the same update.' } })
    else await route.fulfill({ response })
  })
  await page.getByRole('button', { name: 'Save store actions', exact: true }).click()
  await expect(panel.getByRole('alert')).toContainText('Retry the same update')
  await page.getByRole('button', { name: 'Save store actions', exact: true }).click()
  await expect(panel.getByRole('status')).toContainText('Store actions saved')
  expect(operations[0]).toBe(operations[1])
  await expect(panel.locator('.workflow-summary')).toContainText('In Progress')
  await expect(panel.getByRole('link', { name: 'Open email draft' })).toHaveAttribute('href', /^mailto:customer%40example.com\?subject=/)
  await expect(panel.locator('.workflow-summary')).toContainText('Customer not contacted')
  await page.getByRole('link', { name: 'Insights', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: `Open feedback ${saved.feedbackId}` }).click()
  await expect(page.getByLabel('Assigned colleague', { exact: true })).toHaveValue('Alex Example')
  await page.getByLabel('Work status', { exact: true }).selectOption('resolved')
  await page.getByLabel('Action taken', { exact: true }).fill('Duplicate charge refunded and payment references checked.')
  await panel.getByLabel('Customer Communication', { exact: true }).fill('The duplicate charge has been refunded.')
  await page.getByLabel('Contact record', { exact: true }).selectOption('contact_recorded')
  await page.getByRole('button', { name: 'Save store actions', exact: true }).click()
  await expect(panel.locator('.workflow-summary')).toContainText('Resolved')
  await expect(panel.locator('.workflow-summary')).toContainText('Contact recorded by colleague')
  await panel.getByText('Saved action history (2)', { exact: true }).click()
  await expect(panel.locator('ol li')).toHaveCount(2)
  for (const width of [320, 390, 768, 1440]) {
    await page.setViewportSize({ width, height: 1000 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  }
  await page.screenshot({ path: path.join(screenshots, 'store-actions-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: path.join(screenshots, 'store-actions-mobile.png'), fullPage: true })
  const workflow = await (await page.request.get(`/api/tickets/${saved.ticket.id}/workflow`)).json()
  expect(workflow.version).toBe(2)
  expect(workflow.status).toBe('resolved')
  expect(workflow.history).toHaveLength(2)
})

test('saved-history outage is visible and refresh recovers', async ({ page }) => {
  await page.route('**/api/feedback', route => route.fulfill({ status: 503, json: { detail: 'Feedback storage unavailable' } }))
  await page.goto('/#insights')
  await expect(page.getByRole('alert')).toContainText('Saved feedback is unavailable')
  await expect(page.getByRole('heading', { name: 'No analyses yet' })).toHaveCount(0)
  await page.unroute('**/api/feedback')
  await page.getByRole('button', { name: 'Refresh saved feedback' }).click()
  await expect(page.getByRole('heading', { name: 'No analyses yet' })).toBeVisible()
  await page.getByRole('link', { name: 'Feedback', exact: true }).click()
  await page.route('**/api/predict', route => route.fulfill({ status: 503, json: { detail: 'Feedback storage unavailable. Please retry.' } }))
  await page.getByRole('button', { name: 'Analyse feedback', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('could not be confirmed as saved')
  await expect(page.locator('.saved-feedback')).toHaveCount(0)
})